import Head from 'next/head';

import TablatureControls from '@modules/tablatureEditor/components/controls/TablatureControls';
import Tablature from '@modules/tablatureEditor/components/Tablature';
import { useTablatureStore } from '@modules/tablatureStore/useTablatureStore';
import styles from '@styles/pages/index.module.scss';

export default function Home() {
	const tablature = useTablatureStore().tablature;

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<Tablature tablature={tablature} />
				<TablatureControls />
			</main>
		</>
	);
}
